'use strict';

const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const { readJSON } = require('../utils/file-io');

/**
 * Format today's date as "Month DD, YYYY".
 */
function formatDateLong(date) {
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

/**
 * Truncate string to maxLen chars, appending '...' if truncated.
 */
function trunc(str, maxLen) {
  if (!str) return '';
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen) + '...';
}

/**
 * Load a profile JSON file, returning null if missing.
 */
function loadProfile(dataDir, filename) {
  const p = path.join(dataDir, 'profile', filename);
  try {
    return fs.existsSync(p) ? readJSON(p) : null;
  } catch (_) {
    return null;
  }
}

/**
 * Draw a horizontal rule on the PDFDocument.
 */
function drawRule(doc) {
  doc.moveTo(72, doc.y)
    .lineTo(doc.page.width - 72, doc.y)
    .strokeColor('#cccccc')
    .lineWidth(0.5)
    .stroke();
  doc.moveDown(0.5);
}

/**
 * Draw a section heading.
 */
function sectionHeading(doc, title) {
  doc.moveDown(0.8);
  doc.font('Helvetica-Bold').fontSize(14).fillColor('#222222').text(title);
  doc.moveDown(0.3);
}

/**
 * Draw footer on each page.
 */
function drawFooter(doc, dateStr) {
  const bottom = doc.page.height - 54;
  const left = 72;
  const width = doc.page.width - 144;
  doc
    .font('Helvetica').fontSize(9).fillColor('#999999')
    .text(`Generated by Admissions Officer | ${dateStr}`, left, bottom, { width, align: 'center' })
    .text('This is a summary — full profile data available as JSON export.', left, doc.y, { width, align: 'center' });
}

/**
 * Generate a PDF of the student's profile and pipe it to the response stream.
 * @param {string} dataDir
 * @param {NodeJS.WritableStream} outputStream
 * @returns {Promise<void>}
 */
function generateProfilePDF(dataDir, outputStream) {
  return new Promise((resolve, reject) => {
    try {
      const metadata = loadProfile(dataDir, '.metadata.json') || {};
      const academic = loadProfile(dataDir, 'academic.json') || {};
      const tests = loadProfile(dataDir, 'tests.json');
      const achievements = loadProfile(dataDir, 'achievements.json');
      const activities = loadProfile(dataDir, 'activities.json');
      const impactStatements = loadProfile(dataDir, 'impact_statements.json');

      const firstName = metadata.firstName || 'Student';
      const today = new Date();
      const dateStr = formatDateLong(today);

      const doc = new PDFDocument({ size: 'LETTER', margins: { top: 72, bottom: 72, left: 72, right: 72 }, autoFirstPage: true });

      doc.on('error', (err) => reject(err));
      outputStream.on('error', (err) => reject(err));
      doc.pipe(outputStream);

      // Hook for footers
      const footerPages = [];
      doc.on('pageAdded', () => { footerPages.push(doc.bufferedPageRange ? doc.bufferedPageRange() : null); });

      // ── Header ──────────────────────────────────────────────────────────────
      doc.font('Helvetica-Bold').fontSize(20).fillColor('#000000').text(firstName);
      doc.font('Helvetica').fontSize(12).fillColor('#666666').text('Admissions Officer — Profile Summary');
      doc.moveDown(0.5);
      drawRule(doc);

      // ── Academic Summary ────────────────────────────────────────────────────
      sectionHeading(doc, 'Academic Summary');
      doc.font('Helvetica').fontSize(11).fillColor('#000000');

      const gpa = academic.gpa !== undefined ? academic.gpa : null;
      if (gpa !== null) doc.text(`GPA: ${gpa}`);

      const school = academic.schoolName || academic.school || null;
      if (school) doc.text(`School: ${school}`);

      const courses = Array.isArray(academic.courses) ? academic.courses : [];
      if (courses.length > 0) {
        const shownCourses = courses.slice(0, 10);
        let courseText = `Courses: ${shownCourses.join(', ')}`;
        if (courses.length > 10) courseText += `, ...and ${courses.length - 10} more`;
        doc.text(courseText, { lineGap: 3 });
      }

      if (gpa === null && !school && courses.length === 0) {
        doc.text('No academic data recorded.', { color: '#666666' });
      }

      // ── Test Scores ─────────────────────────────────────────────────────────
      sectionHeading(doc, 'Test Scores');
      doc.font('Helvetica').fontSize(11).fillColor('#000000');

      const testList = Array.isArray(tests) ? tests : (tests && Array.isArray(tests.tests) ? tests.tests : []);
      if (testList.length === 0) {
        doc.text('No test scores recorded.');
      } else {
        testList.forEach((t) => {
          const name = t.testName || t.name || 'Unknown Test';
          const score = t.score !== undefined ? t.score : '—';
          doc.text(`${name}: ${score}`);
        });
      }

      // ── Achievements ────────────────────────────────────────────────────────
      sectionHeading(doc, 'Achievements');
      doc.font('Helvetica').fontSize(11).fillColor('#000000');

      const achList = Array.isArray(achievements) ? achievements : (achievements && Array.isArray(achievements.achievements) ? achievements.achievements : []);
      if (achList.length === 0) {
        doc.text('No achievements recorded.');
      } else {
        const shown = achList.slice(0, 10);
        shown.forEach((a) => {
          const title = a.title || 'Achievement';
          const desc = trunc(a.description || '', 120);
          doc.text(`• ${title}${desc ? ' — ' + desc : ''}`, { indent: 10, lineGap: 3 });
        });
        if (achList.length > 10) {
          doc.font('Helvetica').fontSize(10).fillColor('#666666')
            .text(`...and ${achList.length - 10} more achievements in your full profile.`, { indent: 10 });
          doc.fillColor('#000000').fontSize(11);
        }
      }

      // ── Activities ──────────────────────────────────────────────────────────
      sectionHeading(doc, 'Activities');
      doc.font('Helvetica').fontSize(11).fillColor('#000000');

      const actList = Array.isArray(activities) ? activities : (activities && Array.isArray(activities.activities) ? activities.activities : []);
      if (actList.length === 0) {
        doc.text('No activities recorded.');
      } else {
        const shown = actList.slice(0, 10);
        shown.forEach((a) => {
          const name = a.name || 'Activity';
          const role = a.role ? `, ${a.role}` : '';
          const dur = a.duration ? ` (${a.duration})` : '';
          doc.text(`• ${name}${role}${dur}`, { indent: 10, lineGap: 3 });
        });
        if (actList.length > 10) {
          doc.font('Helvetica').fontSize(10).fillColor('#666666')
            .text(`...and ${actList.length - 10} more.`, { indent: 10 });
          doc.fillColor('#000000').fontSize(11);
        }
      }

      // ── Impact Statements ───────────────────────────────────────────────────
      sectionHeading(doc, 'Impact Statements');
      doc.font('Helvetica').fontSize(11).fillColor('#000000');

      const allStmts = Array.isArray(impactStatements) ? impactStatements
        : (impactStatements && Array.isArray(impactStatements.impact_statements) ? impactStatements.impact_statements
        : (impactStatements && Array.isArray(impactStatements.statements) ? impactStatements.statements : []));

      if (allStmts.length === 0) {
        doc.text('No impact statements recorded.');
      } else {
        const approved = allStmts.filter((s) => s.status === 'approved');
        let shown = approved.slice(0, 5);
        if (shown.length < 5) {
          const drafts = allStmts.filter((s) => s.status !== 'approved');
          shown = shown.concat(drafts.slice(0, 5 - shown.length));
        }
        shown.forEach((s) => {
          const text = trunc(s.text || s.statement || '', 300);
          doc.font('Helvetica').fontSize(11).fillColor('#444444')
            .text(`"${text}"`, { indent: 20, lineGap: 4 });
          doc.moveDown(0.3);
        });
      }

      // ── Footer on first page ──────────────────────────────────────────────
      drawFooter(doc, dateStr);

      doc.end();

      // When the output stream finishes, resolve
      outputStream.on('finish', () => resolve());
      // If doc ends before outputStream finish, we rely on outputStream finish event
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateProfilePDF };
