'use strict';

const fs = require('fs');
const path = require('path');
const archiverLib = require('archiver');
const { readJSON } = require('../utils/file-io');

const PROFILE_FILES = [
  'academic.json',
  'tests.json',
  'achievements.json',
  'activities.json',
  'impact_statements.json',
  'essays.json',
  '.metadata.json',
];

const README_TEXT = `This archive was generated by Admissions Officer. It contains your structured profile data as JSON files. You can re-import this into a new AO instance or open any file in a text editor. Original uploaded documents are not included — access them from your data directory.`;

/**
 * Stream a zip archive of the profile JSON files to the given writable stream.
 * @param {string} dataDir
 * @param {NodeJS.WritableStream} outputStream
 * @returns {Promise<void>}
 */
function streamProfileZip(dataDir, outputStream) {
  return new Promise((resolve, reject) => {
    const profileDir = path.join(dataDir, 'profile');

    const archive = new archiverLib.ZipArchive({ zlib: { level: 6 } });

    archive.on('error', (err) => reject(err));
    outputStream.on('error', (err) => reject(err));
    archive.on('finish', () => resolve());

    archive.pipe(outputStream);

    // Add README
    archive.append(README_TEXT, { name: 'README.txt' });

    // Add profile files
    for (const filename of PROFILE_FILES) {
      const filePath = path.join(profileDir, filename);
      if (fs.existsSync(filePath)) {
        archive.file(filePath, { name: `profile/${filename}` });
      }
    }

    archive.finalize();
  });
}

/**
 * Check which profile files exist and return their names (minus missing ones).
 * Returns { files: string[], allMissing: boolean }
 */
function getExistingProfileFiles(dataDir) {
  const profileDir = path.join(dataDir, 'profile');
  const files = PROFILE_FILES.filter((f) => fs.existsSync(path.join(profileDir, f)));
  return { files, allMissing: files.length === 0 };
}

module.exports = { streamProfileZip, getExistingProfileFiles, PROFILE_FILES };
